// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf2wud201utBFU7SrBf_J-eqvqKMnADNA',
    appId: '1:106105676686:android:fd23e3f3201f4b246cbadf',
    messagingSenderId: '106105676686',
    projectId: 'credit-converstion',
    storageBucket: 'credit-converstion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgA6i_IHPE6aayOkgcp3XY1xS16d6mEfA',
    appId: '1:106105676686:ios:f25a379f8dcb05036cbadf',
    messagingSenderId: '106105676686',
    projectId: 'credit-converstion',
    storageBucket: 'credit-converstion.appspot.com',
    androidClientId: '106105676686-0m6emu73tgr5a2gs6qoih5n7h4eb3501.apps.googleusercontent.com',
    iosClientId: '106105676686-77ei8hc1f6se9egpijfree7lkh6j2i48.apps.googleusercontent.com',
    iosBundleId: 'creditconversation.com.creditsConversation',
  );
}
